name: 'ci'

on: [workflow_dispatch, push]

jobs:
  run-ui-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [18]
        runOnlyUbuntu:
          # - ${{ github.workspace == '/home/runner/work/github-workspace-conditional-error/github-workspace-conditional-error' }}
          # - ${{startsWith(github.workspace, '/Users/runner/work')}} # both false
          - ${{ startsWith(github.workspace, '/home/runner/work/') }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Show github json
        run: |
          echo "workspace: ${{ github.workspace }}"
          echo "runOnlyUbuntu: ${{ matrix.runOnlyUbuntu }}"
          echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

      - name: Check workspace for macos
        if: startsWith(github.workspace, '/Users/runner/work/')
        run: |
          echo "I'm running on macos-latest: ${{ matrix.os }}"

      - name: Check workspace for ubuntu
        if: startsWith(github.workspace, '/home/runner/work/')
        run: |
          echo "I'm running on ubuntu-latest: ${{ matrix.os }}"