name: 'ci'

on: [workflow_dispatch, push]

jobs:
  run-ui-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [18]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Show github json
        run: |
          echo "workspace: ${{ github.workspace }}"
          echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
        
      - name: Check event_name event with a contains
        if: contains('push', github.event_name)
        run: |
          echo "My event type is: ${{ github.event_name }}"

      - name: Check workspace for macos
        if: contains('/Users/runner/work/', github.workspace)
        run: |
          echo "I'm running on macos-latest: ${{ matrix.os }}"

      - name: Check workspace for ubuntu
        if: contains('/home/runner/work/', github.workspace)
        run: |
          echo "I'm running on ubuntu-latest: ${{ matrix.os }}"